name: foopo
description: "おうちの食料品管理アプリ"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  change_app_package_name: ^1.5.0
  collection: ^1.19.0
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  provider: ^6.1.4
  timezone: ^0.9.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path_android: assets/launcher_icon/android_icon.png
  adaptive_icon_background: "#F1FAFF" #iconの背景色
  adaptive_icon_foreground: assets/launcher_icon/android_icon.png
  image_path_ios: assets/launcher_icon/ios_icon.png
  android: true
  adaptive_icon_padding: true
  min_sdk_android: 30 #Androidの最小SDKバージョン
  ios: true
